// Code generated by github.com/reedom/convergen
// DO NOT EDIT.

package stringer

import (
	"github.com/reedom/convergen/tests/fixtures/data/domain"
	"github.com/reedom/convergen/tests/fixtures/data/model"
)

func LocalToModel(pet *domain.Pet) (dst *model.Pet) {
	dst = &model.Pet{}
	dst.ID = uint64(pet.ID)
	// no match: dst.Category
	dst.Name = pet.Name
	// no match: dst.PhotoUrls
	dst.Status = string(pet.Status)

	return
}
