// Code generated by github.com/reedom/convergen
// DO NOT EDIT.

package typecast

import (
	"github.com/reedom/convergen/tests/fixtures/usecase/typecast/domain"
	"github.com/reedom/convergen/tests/fixtures/usecase/typecast/enums"
	"github.com/reedom/convergen/tests/fixtures/usecase/typecast/model"
)

// DomainToModel converts domain.User to model.User.
// typecast works:
//   - int <-> int64
//   - enums.Status <-> string
//     "enums" package will be imported automatically in the generated code.
func DomainToModel(src *domain.User) (dst *model.User) {
	dst = &model.User{}
	dst.ID = int64(src.ID)
	dst.Name = src.Name
	dst.Status = string(src.Status)

	return
}

func ModelToDomain(src *model.User) (dst *domain.User) {
	dst = &domain.User{}
	dst.ID = int(src.ID)
	dst.Name = src.Name
	dst.Status = enums.Status(src.Status)

	return
}
