// Code generated by github.com/reedom/convergen
// DO NOT EDIT.

package typecast

import (
	"github.com/reedom/convergen/v8/tests/fixtures/usecase/typecast/domain"
	"github.com/reedom/convergen/v8/tests/fixtures/usecase/typecast/enums"
	"github.com/reedom/convergen/v8/tests/fixtures/usecase/typecast/model"
)

// DomainToModel converts domain.User to model.User.
// typecast works:
// - int64 -> int
// - enums.Status -> string
func DomainToModel(src *domain.User) (dst *model.User) {
	dst = &model.User{}
	dst.ID = int64(src.ID)
	dst.Name = src.Name
	dst.Status = string(src.Status)
	dst.Origin.Region = src.Origin.Region

	return
}

// ModelToDomain converts model.User to domain.User.
// typecast works:
//   - int -> int64
//   - string -> enums.Status
//     "enums" package will be imported automatically in the generated code!
func ModelToDomain(src *model.User) (dst *domain.User) {
	dst = &domain.User{}
	dst.ID = int(src.ID)
	dst.Name = src.Name
	dst.Status = enums.Status(src.Status)
	dst.Origin.Region = src.Origin.Region

	return
}
