// Code generated by github.com/reedom/convergen
// DO NOT EDIT.

package converter

import (
	"github.com/reedom/convergen/v8/tests/fixtures/data/model"
	"github.com/reedom/convergen/v8/tests/fixtures/data/model/abc222"
)

func DomainToModel(src *model.Additional, arg0 []abc222.Additional321) (dst *abc222.AdditionalItem123) {
	dst = &abc222.AdditionalItem123{}
	dst.Name = src.Name
	dst.List = arg0

	return
}
