// Code generated by github.com/reedom/convergen
// DO NOT EDIT.

package maps

import (
	"time"
)

type From struct {
	JSONDate JSONDate
}

type To struct {
	JSONDate time.Time
}

type JSONDate time.Time

func (t *JSONDate) Time() time.Time {
	return time.Time(*t)
}

func FromTo(src *From) (dst *To) {
	dst = &To{}
	dst.JSONDate = src.JSONDate.Time()

	return
}
