// Package executor provides a sophisticated execution engine for field mappings with comprehensive
// concurrency control, resource management, and event-driven coordination.
//
// The executor system is designed around clean architecture principles with event-driven coordination
// and field-level concurrency for optimal performance. It works in conjunction with the planner
// to execute generated execution plans with precise resource control and error handling.
//
// Key Components:
//
// 1. Executor: Main interface for coordinating batch execution with event emission
// 2. BatchExecutor: Manages concurrent execution of field mapping batches
// 3. FieldExecutor: Handles individual field mapping execution with strategy dispatch
// 4. ExecutionContext: Provides thread-safe execution context with metrics and cancellation
// 5. ResourcePool: Manages worker pools and memory allocation
// 6. ExecutionMetrics: Collects detailed performance and execution statistics
//
// Architecture:
//
// The execution system follows an event-driven architecture where execution progress is
// communicated through a central event bus. Each execution phase emits appropriate events
// for monitoring, logging, and coordination with other system components.
//
// Concurrency Model:
//
// - Batch-level concurrency: Multiple batches can execute concurrently respecting dependencies
// - Field-level concurrency: Fields within a batch execute concurrently based on resource limits
// - Worker pool management: Dynamic worker allocation based on resource requirements
// - Resource throttling: Memory and CPU usage monitoring with automatic throttling
//
// Error Handling:
//
// - Graceful degradation on resource exhaustion
// - Retry mechanisms for transient failures
// - Context cancellation support for timeout handling
// - Detailed error reporting with execution context
//
// Performance Features:
//
// - Zero-copy execution where possible
// - Memory pool reuse for common operations
// - Adaptive concurrency based on runtime performance
// - Comprehensive metrics for performance analysis
//
// Usage Example:
//
//	executor := executor.NewExecutor(logger, eventBus, config)
//	
//	// Execute a plan generated by the planner
//	ctx := context.Background()
//	result, err := executor.ExecutePlan(ctx, executionPlan)
//	if err != nil {
//		return fmt.Errorf("execution failed: %w", err)
//	}
//	
//	// Access detailed metrics
//	metrics := result.Metrics
//	logger.Info("execution completed",
//		zap.Duration("duration", metrics.TotalDuration),
//		zap.Int("fields_processed", metrics.FieldsProcessed),
//		zap.Float64("throughput", metrics.ThroughputPerSecond))
//
// Thread Safety:
//
// All executor components are designed to be thread-safe and can be used concurrently
// from multiple goroutines. The execution context provides synchronized access to
// shared state and metrics collection.
package executor