// Code generated by github.com/reedom/convergen
// DO NOT EDIT.

package simple

import (
	"github.com/reedom/convergen/tests/fixtures/data/domain"
	"github.com/reedom/convergen/tests/fixtures/data/model"
)

func ToModel(src *domain.Pet) (dst *model.Pet) {
	dst = &model.Pet{}

	return
}
