// Code generated by github.com/reedom/convergen
// DO NOT EDIT.

package simple

import (
	"github.com/reedom/convergen/tests/fixtures/data/ddd/domain"
	"github.com/reedom/convergen/tests/fixtures/data/ddd/model"
)

// DomainToModel copies domain.Pet to model.Pet.
func DomainToModel(pet *domain.Pet) (dst *model.Pet) {
	dst = &model.Pet{}
	dst.ID = pet.ID()
	dst.Category.ID = uint64(pet.Category().ID())
	dst.Category.Name = pet.Category().Name()
	dst.Name = pet.Name()
	dst.Status = pet.Status().String()

	return
}
