// Code generated by github.com/reedom/convergen
// DO NOT EDIT.

package nocase

type ModelA struct {
	ID uint64
}

type ModelB struct {
	id uint64
}

func AtoB(src *ModelA) (dst *ModelB) {
	dst = &ModelB{}
	dst.id = src.ID

	return
}

func BtoA(src *ModelB) (dst *ModelA) {
	dst = &ModelA{}
	dst.ID = src.id

	return
}
