// Code generated by github.com/reedom/convergen
// DO NOT EDIT.

package stringer

import (
	"github.com/reedom/convergen/tests/fixtures/data/model"
	"github.com/reedom/convergen/tests/fixtures/usecase/stringer/local"
)

func LocalToModel(pet *local.Pet) (dst *model.Pet) {
	dst = &model.Pet{}
	dst.ID = pet.ID
	// no match: dst.Category
	dst.Name = pet.Name.String()
	// no match: dst.PhotoUrls
	dst.Status = pet.Status().String()

	return
}
