// Code generated by github.com/reedom/convergen
// DO NOT EDIT.

package mapname

import (
	"github.com/reedom/convergen/tests/fixtures/data/domain"
	"github.com/reedom/convergen/tests/fixtures/data/model"
)

func DomainToModel(cat *domain.Category) (dst *model.Category) {
	dst = &model.Category{}
	dst.CategoryID = uint64(cat.ID)
	dst.Name = cat.Name

	return
}
