// Code generated by github.com/reedom/convergen
// DO NOT EDIT.

package converter

import (
	"github.com/reedom/convergen/tests/fixtures/data/domain"
	"github.com/reedom/convergen/tests/fixtures/data/model"
)

func DomainToModel(pet *domain.Pet) (dst *model.Pet) {
	dst = &model.Pet{}
	// no match: dst.ID
	// no match: dst.Category
	dst.Name = pet.Name
	// no match: dst.PhotoUrls
	// no match: dst.Status

	return
}

func ModelToDomain(src *model.Pet) (dst *domain.Pet, err error) {
	dst = &domain.Pet{}
	// no match: dst.ID
	// no match: dst.Category
	dst.Name = src.Name
	// no match: dst.PhotoUrls
	dst.Status, err = domain.NewPetStatusFromValue(src.Status)
	if err != nil {
		return
	}

	return
}
