// Code generated by github.com/reedom/convergen
// DO NOT EDIT.

package slice

type SrcType struct {
	IntSlice  []int
	DataSlice []Data
}

type DstType struct {
	IntSlice  []int
	DataSlice []Data
}

type Data struct{}

func Copy(src *SrcType) (dst *DstType) {
	dst = &DstType{}
	if src.IntSlice != nil {
		dst.IntSlice = make([]int, len(src.IntSlice))
		copy(dst.IntSlice, src.IntSlice)
	}
	if src.DataSlice != nil {
		dst.DataSlice = make([]Data, len(src.DataSlice))
		for i, e := range src.DataSlice {
			dst.DataSlice[i] = e
		}
	}

	return
}
